import { cp, mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const output = path.join(root, "_site");
const staticFiles = [
  "index.html",
  "styles.css",
  "app.js",
  "content-policy.js",
  "service-worker.js",
  "manifest.webmanifest",
  "favicon.svg",
];

function envValue(name, maxLength = 500) {
  return String(process.env[name] || "").trim().slice(0, maxLength);
}

function parseBoolean(value, fallback) {
  if (!value) return fallback;
  if (/^(1|true|yes)$/i.test(value)) return true;
  if (/^(0|false|no)$/i.test(value)) return false;
  throw new Error("ALLOW_DEMO_MODE must be true or false");
}

function validateHttpsOrigin(value) {
  const url = new URL(value);
  if (url.protocol !== "https:" || url.pathname !== "/" || url.search || url.hash) {
    throw new Error("PAGES_ORIGIN must be an HTTPS origin without a path");
  }
  return url.origin;
}

const supabaseUrl = envValue("SUPABASE_URL");
const supabasePublishableKey = envValue("SUPABASE_PUBLISHABLE_KEY");
const kakaoMapJavaScriptKey = envValue("KAKAO_MAP_JAVASCRIPT_KEY", 120);
const turnstileSiteKey = envValue("TURNSTILE_SITE_KEY", 160);
const pagesOrigin = validateHttpsOrigin(envValue("PAGES_ORIGIN") || "https://kjhljh0702.github.io");
const hasCloudConfig = Boolean(supabaseUrl && supabasePublishableKey);

if (Boolean(supabaseUrl) !== Boolean(supabasePublishableKey)) {
  throw new Error("SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY must be configured together");
}
if (supabaseUrl && (new URL(supabaseUrl).protocol !== "https:" || !supabaseUrl.endsWith(".supabase.co"))) {
  throw new Error("SUPABASE_URL must be an HTTPS Supabase project URL");
}
if (supabasePublishableKey && !supabasePublishableKey.startsWith("sb_publishable_")) {
  throw new Error("Only an sb_publishable_ key may be exposed to the browser");
}

const allowDemoMode = parseBoolean(envValue("ALLOW_DEMO_MODE", 10), !hasCloudConfig);
const publicConfig = {
  supabaseUrl,
  supabasePublishableKey,
  kakaoMapJavaScriptKey,
  turnstileSiteKey,
  allowedOAuthRedirectOrigins: ["http://localhost:4173", pagesOrigin],
  allowDemoMode,
};

await rm(output, { recursive: true, force: true });
await mkdir(output, { recursive: true });
await Promise.all(staticFiles.map((file) => cp(path.join(root, file), path.join(output, file))));
await cp(path.join(root, "assets"), path.join(output, "assets"), { recursive: true });
await writeFile(path.join(output, ".nojekyll"), "", "utf8");
await writeFile(
  path.join(output, "config.js"),
  `// Generated by scripts/build-pages.mjs. Public browser configuration only.\nwindow.APP_CONFIG = Object.freeze(${JSON.stringify(publicConfig, null, 2)});\n`,
  "utf8",
);

console.log(`pages-build: ${staticFiles.length + 2} entries prepared, cloud=${hasCloudConfig}, demo=${allowDemoMode}`);
